/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package www.laboratorio6p2_salvadormacias;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Apple
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_opciones = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        boton_retirar = new javax.swing.JButton();
        boton_depositar = new javax.swing.JButton();
        frame_retiro = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label_nombre_retiro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_saldo_retiro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_saldoRetirar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        frame_deposito = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_cantidadDepositar = new javax.swing.JTextField();
        boton_transferir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_cuentaTransferencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_cuentaTransferencia1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        boton_sesion = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        boton_retirar.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        boton_retirar.setText("retirar dinero");
        boton_retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_retirarMouseClicked(evt);
            }
        });
        boton_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_retirarActionPerformed(evt);
            }
        });

        boton_depositar.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        boton_depositar.setText("depositar/transferir");
        boton_depositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_depositarMouseClicked(evt);
            }
        });
        boton_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_depositarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(boton_retirar)
                .addGap(53, 53, 53)
                .addComponent(boton_depositar)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_retirar)
                    .addComponent(boton_depositar))
                .addGap(172, 172, 172))
        );

        javax.swing.GroupLayout frame_opcionesLayout = new javax.swing.GroupLayout(frame_opciones.getContentPane());
        frame_opciones.getContentPane().setLayout(frame_opcionesLayout);
        frame_opcionesLayout.setHorizontalGroup(
            frame_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_opcionesLayout.setVerticalGroup(
            frame_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Saldo actual:");

        jLabel5.setText("Saldo a retirar:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(label_nombre_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_saldo_retiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_saldoRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_nombre_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_saldo_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(label_saldoRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 380, 190));

        jButton1.setText("0");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 70, 60));

        jButton2.setText("1");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 70, 50));

        jButton3.setText("4");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 60));

        jButton4.setText("7");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 70, 50));

        jButton5.setBackground(new java.awt.Color(0, 255, 102));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 70, 60));

        jButton6.setText("2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 70, 50));

        jButton7.setText("5");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, 60));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 383, 70, 50));

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, 60));

        jButton10.setText("3");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 70, 50));

        jButton11.setText("6");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 70, 50));

        jButton12.setText("9");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 70, 50));

        javax.swing.GroupLayout frame_retiroLayout = new javax.swing.GroupLayout(frame_retiro.getContentPane());
        frame_retiro.getContentPane().setLayout(frame_retiroLayout);
        frame_retiroLayout.setHorizontalGroup(
            frame_retiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        frame_retiroLayout.setVerticalGroup(
            frame_retiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setText("Transferir");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 120, 40));

        jLabel7.setText("cantidad a depositar:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        text_cantidadDepositar.setText("   ");
        jPanel5.add(text_cantidadDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 120, 30));

        boton_transferir.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        boton_transferir.setText("Transferir");
        boton_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_transferirActionPerformed(evt);
            }
        });
        jPanel5.add(boton_transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setText("Depositar");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 120, 40));

        jLabel9.setText("cuenta de la persona a transferir:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));
        jPanel5.add(text_cuentaTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, 30));

        jLabel10.setText("cantidad a transferir: ");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));
        jPanel5.add(text_cuentaTransferencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, 30));

        jButton14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton14.setText("Depositar");
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        javax.swing.GroupLayout frame_depositoLayout = new javax.swing.GroupLayout(frame_deposito.getContentPane());
        frame_deposito.getContentPane().setLayout(frame_depositoLayout);
        frame_depositoLayout.setHorizontalGroup(
            frame_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_depositoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frame_depositoLayout.setVerticalGroup(
            frame_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, 30));

        jLabel2.setText("usuario: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 30));
        jPanel1.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, 40));

        jLabel3.setText("contrasena");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, 40));

        boton_sesion.setText("iniciar sesion");
        boton_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_sesionMouseClicked(evt);
            }
        });
        jPanel1.add(boton_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 333, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void boton_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_transferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_transferirActionPerformed

    private void boton_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_sesionMouseClicked
        /* if (lista_usuarios.contains(text_usuario.getText())) {

            this.setVisible(false);
            text_usuario.setText("");
            jPasswordField1.setText("");
            frame_opciones.setVisible(true);
            frame_opciones.pack();
            frame_opciones.setLocationRelativeTo(this);

        } else {
            System.out.println("para ingresar al menu de opciones primero cree un usuario...");

        }*/
        this.setVisible(false);
        text_usuario.setText("");
        jPasswordField1.setText("");
        frame_opciones.setVisible(true);
        frame_opciones.pack();
        frame_opciones.setLocationRelativeTo(this);

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_sesionMouseClicked

    private void boton_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_depositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_depositarActionPerformed

    private void boton_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_retirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_retirarActionPerformed

    private void boton_retirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_retirarMouseClicked
        frame_opciones.setVisible(false);
        frame_retiro.setVisible(true);
        frame_retiro.pack();
        frame_retiro.setLocationRelativeTo(this);

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_retirarMouseClicked

    private void boton_depositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_depositarMouseClicked
        frame_opciones.setVisible(false);
        frame_deposito.setVisible(true);
        frame_deposito.pack();
        frame_deposito.setLocationRelativeTo(this);
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_depositarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
                /*boolean salida = false;
                do {
                    System.out.println("Menu: ");
                    System.out.println("1. crear usuario normal ");
                    System.out.println("2. crear usuario premium ");
                    System.out.println("3. salir");
                    int opcion = lea.nextInt();
                    switch (opcion) {
                        case 1: {
                            crear_normal();
                        }

                        break;
                        case 2: {
                            crear_premium();
                        }
                        break;
                        case 3: {
                            salida = true;
                            System.out.println("se abandonara el programa");
                        }
                        break;
                        default:
                            System.out.println("opcion ingresada es invalida...");
                    }

                } while (salida != true);*/

            }
        });
    }

    public static void crear_normal() {
        System.out.println("ingrese el nombre: ");
        String nombre = str.nextLine();
        System.out.println("Ingrese el usuario: ");
        String usuario = str.nextLine();
        System.out.println("Ingrese la contrasena: ");
        String contrasena = str.nextLine();
        System.out.println("Ingrese el dinero: ");
        double dinero = lea.nextDouble();
        System.out.println("Ingrese el numero de cuenta: ");
        int cuenta = lea.nextInt();
        lista_usuarios.add(new normal(nombre, usuario, contrasena, dinero, cuenta));
        System.out.println("se creo el usuario exitosamente...");

    }

    public static void crear_premium() {
        System.out.println("ingrese el nombre: ");
        String nombre = str.nextLine();
        System.out.println("Ingrese el usuario: ");
        String usuario = str.nextLine();
        System.out.println("Ingrese la contrasena: ");
        String contrasena = str.nextLine();
        System.out.println("Ingrese el dinero: ");
        double dinero = lea.nextDouble();
        dinero = +3000;
        System.out.println("Ingrese el numero de cuenta: ");
        int cuenta = lea.nextInt();
        lista_usuarios.add(new premium(nombre, usuario, contrasena, dinero, cuenta));
        System.out.println("se creo el usuario exitosamente...");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_depositar;
    private javax.swing.JButton boton_retirar;
    private javax.swing.JButton boton_sesion;
    private javax.swing.JButton boton_transferir;
    private javax.swing.JFrame frame_deposito;
    private javax.swing.JFrame frame_opciones;
    private javax.swing.JFrame frame_retiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel label_nombre_retiro;
    private javax.swing.JLabel label_saldoRetirar;
    private javax.swing.JLabel label_saldo_retiro;
    private javax.swing.JTextField text_cantidadDepositar;
    private javax.swing.JTextField text_cuentaTransferencia;
    private javax.swing.JTextField text_cuentaTransferencia1;
    private javax.swing.JTextField text_usuario;
    // End of variables declaration//GEN-END:variables
  public static ArrayList<usuario> lista_usuarios = new ArrayList<>();
    public static Scanner lea = new Scanner(System.in);
    public static Scanner str = new Scanner(System.in);

}
